name: pull_request
on:
  pull_request:
    branches:
      - master
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - uses: wagoid/commitlint-github-action@v4
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
  validate:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node

      - name: validate (lint)
        run: yarn lint
  test:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node

      - name: run test
        run: yarn test --collectCoverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: test run generator API markdown
        run: .husky/generate-api-md
