name: release
on:
  push:
    branches:
      - master
      - next
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - uses: wagoid/commitlint-github-action@v4
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules

  validate:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node

      - name: validate (lint)
        run: pnpm run lint
  test:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node

      - name: run test
        run: pnpm run test --collectCoverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  release:
    needs:
      - validate
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0.2
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'master', 
              'next', 
              'next-major', 
              {
                name: 'beta', 
                prerelease: true
              }, 
              {
                name: 'alpha', 
                prerelease: true
              }
            ]
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semrel-extra/npm
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_EMAIL: 'isfawwaz@gmail.com'
          GIT_COMMITTER_EMAIL: 'isfawwaz@gmail.com'
          GIT_AUTHOR_NAME: 'isfawwaz'
          GIT_COMMITTER_NAME: 'isfawwaz'
